version: '3.5'

services:
  postgres:
    container_name: bix_output_postgres
    image: postgres
    environment:
      POSTGRES_USER: bix_user
      POSTGRES_PASSWORD: bix_password
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped


networks:
  postgres:
    driver: bridge

volumes:
    postgres:
